stages:
  - fmt
  - tests
  - quality
  - publish

.rust_stable_lin64:
  image: registry.duniter.org/docker/rust/rust-x64-stable-ci:latest
  tags:
    - redshift-docker-runner
  before_script:
    - export PATH="$HOME/.cargo/bin:$PATH"
    - rustup show
    - rustc --version && cargo --version

fmt:
  extends: .rust_stable_lin64
  stage: fmt
  before_script:
    - cargo fmt -- --version
  script:
    - cargo fmt -- --check
        
tests:linux64:stable:
  extends: .rust_stable_lin64
  stage: tests
  tags:
    - redshift-docker-runner
  script: 
    - cd cli
    - RUSTFLAGS="-D warnings" cargo build
    - cargo test --all

clippy:
  extends: .rust_stable_lin64
  before_script:
    - cargo clippy -- -V
  stage: quality
  script:
    - cargo clippy --all -- -D warnings --verbose
    
audit_dependencies:
  extends: .rust_stable_lin64
  before_script:
    - cargo deny -V
  stage: quality
  script:
    - cargo deny check

publish:
  extends: .rust_stable_lin64
  stage: publish
  only:
    - tags
  script:
    - cargo login $CRATES_IO_TOKEN
    - cargo publish
